[project]
name = "cosyvoice"
description = "Support both CosyVoice1.0 and CosyVoice2.0. Referenced [a/CosyVoice-ComfyUI](https://github.com/AIFSH/CosyVoice-ComfyUI), the following modifications have been made: Add support for CosyVoice2.0, Add whether to use stream processing options, Use speed control by CosyVoice, Add model path check to avoid duplicate downloads, Provide two ways of use"
version = "1.0.0"
license = {file = "LICENSE"}
dependencies = ["--extra-index-url https://download.pytorch.org/whl/cu121", "--extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/ # https://github.com/microsoft/onnxruntime/issues/21684", "conformer==0.3.2", "deepspeed==0.14.2; sys_platform == 'linux'", "diffusers==0.29.0", "gdown==5.1.0", "gradio==5.4.0", "grpcio==1.57.0", "grpcio-tools==1.57.0", "hydra-core==1.3.2", "HyperPyYAML==1.2.2", "inflect==7.3.1", "librosa==0.10.2", "lightning==2.2.4", "matplotlib==3.7.5", "modelscope==1.15.0", "networkx==3.1", "omegaconf==2.3.0", "onnx==1.16.0", "onnxruntime-gpu==1.18.0; sys_platform == 'linux'", "onnxruntime==1.18.0; sys_platform == 'darwin' or sys_platform == 'windows'", "openai-whisper==20231117", "protobuf==4.25", "pydantic==2.7.0", "rich==13.7.1", "soundfile==0.12.1", "tensorboard==2.14.0", "tensorrt-cu12==10.0.1; sys_platform == 'linux'", "tensorrt-cu12-bindings==10.0.1; sys_platform == 'linux'", "tensorrt-cu12-libs==10.0.1; sys_platform == 'linux'", "torch==2.3.1", "torchaudio==2.3.1", "transformers==4.40.1", "uvicorn==0.30.0", "wget==3.2", "fastapi==0.115.6", "fastapi-cli==0.0.4", "WeTextProcessing==1.0.3"]

[project.urls]
Repository = "https://github.com/SshunWang/ComfyUI_CosyVoice"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "ComfyUI_CosyVoice"
Icon = ""
